### ISSUE TITLE
Snapshot Command : Extra features

### ISSUE THREAD

**Issue by thrijith** [wposs/snapshot-command#4]
Allow creating :

 - [x] Possibly add support to push snapshot to remote installation using aliases 
 - [x] `wp snapshot pull` ( Allow downloading backup from third-party storages )

**Comment by abhijitrakas** [comment]
@thrijith @schlessera 

I am bit confuse about the `wp snapshot pull` command process. I have two solutions to accomplish this

When run `wp snapshot pull S3-zip-filename`

Solution One:

Command will fetch snapshot zip from S3. On download complete command will create a record on the basis of the backup date (We will store the backup Date in the snapshot configuration file). Then the user can restore that backup using a snapshot ID.


Solution Two:

In this solution, we need to add a new column in the database (could be `location`). In this column default value will be "system" which means snapshot stored in the local system. So when we create a snapshot, the `location` column will always be "system".

Then, when we push that snapshot to S3 this column will change to "S3" which means snapshot stored in S3. Once the snapshot successfully uploaded to S3 we should remove that snapshot files from the System (as it's now stored on S3). Remember we are not removing records from the database.

Now when the user tries to restore that snapshot we will check the location first. If the location is S3 then pull snapshot files from S3 and restore all data and database. Once all restored we can remove that downloaded snapshot files from local (as its already available on S3).


Please let me know your thoughts. It will be very helpful.

**Comment by abhijitrakas** [comment]
> Possibly add support to push snapshot to remote installation using aliases

@thrijith Can you please add more details about ☝️ ?

**Comment by thrijith** [comment]
> Can you please add more details about ☝️ ?

Sure, so the idea was to use details added in config for alias and use that to pull/push the zip of snapshot to the server.

When an alias is added, something similar as below can be found in the `.wp-cli/config.yml` file

```
@remoteserver:
 ssh: >
   root@192.168.0.1/path/to/wordpress/install
```

We can use above details to do an `rsync` when user does something like `wp snapshot push 1 @remoteserver`, On pull/push create record, on remote if command doesn't exist, it will throw error else no issues, please let me know if that helps. Thanks!
